/**
 * Energi Tech affordable solar packages (USD).
 * Package price includes supply + installation in Harare only.
 */

export const PACKAGE_PRICE_NOTE =
  "Package prices include full installation in Harare. Outside Harare: $0.50 per km delivery (enter your area).";

export const OUTSIDE_DELIVERY_PER_KM_USD = 0.5;

export const PACKAGES = [
  {
    id: "3.2kva-basic",
    name: "3.2Kva BASIC Package",
    kva: 3.2,
    price: 950,
    panelCount: 3,
    panelW: 550,
    batteryCount: 1,
    includes: [
      "3.2kva Hybrid Inverter",
      "1x 24v 100Ah Lithium Ion Battery",
      "3x 550w JINKO Solar Panels",
      "Mounting Kit",
      "Accessories",
      "Automatic ChangeOver Switch",
      "Adjustable Voltage Switcher",
      "Labour | Installation",
      "5-7 Years Warranty | maintenance",
    ],
    powers: [
      "Upright Fridge",
      "TV and Radio",
      "WiFi and CCTVs",
      "Lights",
      "Washing Machine",
      "Printers and other appliances",
    ],
  },
  {
    id: "3.5kva",
    name: "3.5Kva Package",
    kva: 3.5,
    price: 1100,
    panelCount: 4,
    panelW: 550,
    batteryCount: 1,
    includes: [
      "3.5kva Hybrid Inverter",
      "1x 24v 150Ah Lithium Ion Battery",
      "4x 550w JINKO Solar Panels",
      "Mounting Kit",
      "Accessories",
      "Automatic ChangeOver Switch",
      "Adjustable Voltage Switcher",
      "Labour | Installation",
      "5-7 Years Warranty | maintenance",
    ],
    powers: [
      "Upright Fridge",
      "Deep Freezer",
      "TV and Radio",
      "WiFi and CCTVs",
      "Lights",
      "Washing Machine",
      "Borehole Pump",
      "Printers and other appliances",
    ],
  },
  {
    id: "4.2kva",
    name: "4.2Kva Package",
    kva: 4.2,
    price: 1250,
    panelCount: 5,
    panelW: 550,
    batteryCount: 1,
    includes: [
      "4.2kva Hybrid Inverter",
      "1x 24v 200Ah Lithium Ion Battery",
      "5x 550w JINKO Solar Panels",
      "Mounting Kit",
      "Accessories",
      "Automatic ChangeOver Switch",
      "Adjustable Voltage Switcher",
      "Labour | Installation",
      "5-7 Years Warranty | maintenance",
    ],
    powers: [
      "Upright Fridge",
      "Deep Freezer",
      "TV and Radio",
      "WiFi and CCTVs",
      "Lights",
      "Washing Machine",
      "Borehole Pump",
      "Printers and other appliances",
    ],
  },
  {
    id: "5.5kva-lite",
    name: "5.5Kva LITE Package",
    kva: 5.5,
    price: 1500,
    panelCount: 6,
    panelW: 550,
    batteryCount: 1,
    includes: [
      "5.5kva Hybrid Inverter",
      "1x 24v 200Ah Lithium Ion Battery",
      "6x 550w JINKO Solar Panels",
      "Mounting Kit",
      "Accessories",
      "Automatic ChangeOver Switch",
      "Adjustable Voltage Switcher",
      "Labour | Installation",
      "5-7 Years Warranty | maintenance",
    ],
    powers: [
      "Upright Fridge",
      "TV and Radio",
      "WiFi and CCTVs",
      "Lights",
      "Washing Machine",
      "Borehole Pump",
      "Printers and other appliances",
    ],
  },
  {
    id: "6.2kva-lite",
    name: "6.2Kva LITE Package",
    kva: 6.2,
    price: 1600,
    panelCount: 4,
    panelW: 550,
    batteryCount: 1,
    includes: [
      "6.2kva Hybrid Inverter",
      "1x 48v 100Ah Lithium Ion Battery",
      "4x 550w ALL WEATHER Mono Panels",
      "Mounting Kit",
      "Accessories",
      "Automatic ChangeOver Switch",
      "Adjustable Voltage Switcher",
      "Labour | Installation",
      "5-7 Years Warranty | maintenance",
    ],
    powers: [
      "Upright Fridge",
      "Deep Freezer",
      "TV and Radio",
      "WiFi and CCTVs",
      "Lights",
      "Washing Machine",
      "Borehole Pump",
      "Printers and other appliances",
    ],
  },
  {
    id: "6.5kva",
    name: "6.5Kva Package",
    kva: 6.5,
    price: 1900,
    panelCount: 6,
    panelW: 550,
    batteryCount: 1,
    includes: [
      "6.5kva Hybrid Inverter",
      "1x 48v 200Ah Lithium Ion Battery",
      "6x 550w ALL WEATHER Mono Panels",
      "Mounting Kit",
      "Accessories",
      "Automatic ChangeOver Switch",
      "Adjustable Voltage Switcher",
      "Labour | Installation",
      "5-7 Years Warranty | maintenance",
    ],
    powers: [
      "Upright Fridge",
      "Deep Freezer",
      "TV and Radio",
      "WiFi and CCTVs",
      "Lights",
      "Washing Machine",
      "Borehole Pump",
      "Printers and other appliances",
    ],
  },
  {
    id: "8.2kva",
    name: "8.2Kva Package",
    kva: 8.2,
    price: 2200,
    panelCount: 8,
    panelW: 550,
    batteryCount: 1,
    includes: [
      "8.2kva Hybrid Inverter",
      "1x 48v 200Ah Lithium Ion Battery",
      "8x 550w ALL WEATHER Mono Panels",
      "Mounting Kit",
      "Accessories",
      "Automatic ChangeOver Switch",
      "Adjustable Voltage Switcher",
      "Labour | Installation",
      "5-7 Years Warranty | maintenance",
    ],
    powers: [
      "Upright Fridge",
      "Deep Freezer",
      "TV and Radio",
      "WiFi and CCTVs",
      "Lights",
      "Washing Machine",
      "Borehole Pump",
      "Printers and other appliances",
    ],
  },
  {
    id: "10.2kva",
    name: "10.2Kva Package",
    kva: 10.2,
    price: 3400,
    panelCount: 12,
    panelW: 550,
    batteryCount: 2,
    includes: [
      "10.2kva Hybrid Inverter",
      "2x 48v 200Ah Lithium Ion Battery",
      "12x 550w ALL WEATHER Mono Panels",
      "Mounting Kit",
      "Accessories",
      "Automatic ChangeOver Switch",
      "Adjustable Voltage Switcher",
      "Labour | Installation",
      "5-7 Years Warranty | maintenance",
    ],
    powers: [
      "Full household / office back-up",
      "Air conditioning",
      "Electric Gate",
      "Swimming Pool Pump",
      "And other high-power appliances",
    ],
  },
];

export function getPackageById(id) {
  return PACKAGES.find((p) => p.id === id) || null;
}
